### ISSUE TITLE
Does not support Django 2.0

### ISSUE THREAD

**Issue by rajkrisoff5** [tixdo/votes#8]
Tried to use the package with Django 2.0. Gives back the error: "class Vote(models.Model):
 TypeError: __init__() missing 1 required positional argument: 'on_delete'"
 The requirements seems too mention django>=1.9.1. Maybe either change the requirements, or add support to Django 2.0.

**Comment by abhinavsohani** [comment]
Merged https://github.com/thecodinghouse/votes/pull/9
